name: nutripic
description: "Nutripic App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  path_provider: ^2.0.0
  flutter_dotenv: ^5.1.0
  go_router: ^14.2.7
  http: ^1.2.2
  flutter_vision: ^1.1.4 # YOLO 모델 사용을 위한 패키지 추가

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/yolov8n.tflite # YOLOv8 모델 파일
    - assets/labels.txt # YOLOv8 라벨 파일
  uses-material-design: true

  generate: false
